variable "org_name" {}
variable "api_token" {}
variable "base_url" {}
variable "demo_app_name" { default = "dealer" }
variable "udp_subdomain" { default = "local" }

locals {
  app_domain       = var.udp_subdomain != "local" ? format("%s.%s.unidemo.info") : format("%s.%s", var.udp_subdomain, var.demo_app_name)
  nodash_subdomain = replace(var.udp_subdomain, "-", "_")
}

terraform {
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.17"
    }
  }
}

provider "okta" {
  org_name  = var.org_name
  api_token = var.api_token
  base_url  = var.base_url
}

data "okta_group" "all" {
  name = "Everyone"
}

resource "okta_app_oauth" "dealer" {
  label       = format("%s DEMO (Gerenated by UDP)", local.app_domain)
  type        = "web"
  grant_types = ["authorization_code"]
  redirect_uris = [
    "https://${local.app_domain}/authorization-code/callback",
    "http://localhost:8666/authorization-code/callback"
  ]
  response_types = ["code"]
  consent_method = "TRUSTED"
  issuer_mode    = "ORG_URL"
  lifecycle {
    ignore_changes = [groups]
  }
}

resource "okta_app_group_assignment" "dealer" {
  app_id   = okta_app_oauth.dealer.id
  group_id = data.okta_group.all.id
}

resource "okta_trusted_origin" "dealer_https" {
  name   = format("%s: 8666", local.app_domain)
  origin = "https://${local.app_domain}"
  scopes = ["REDIRECT", "CORS"]
}

resource "okta_auth_server" "dealer" {
  name        = local.app_domain
  description = format("%s (Generated by UDP)", local.app_domain)
  audiences   = ["api://${local.app_domain}"]
}

resource "okta_auth_server_policy" "dealer" {
  auth_server_id   = okta_auth_server.dealer.id
  status           = "ACTIVE"
  name             = "standard"
  description      = "Generated by UDP"
  priority         = 1
  client_whitelist = [okta_app_oauth.dealer.id]
}

resource "okta_auth_server_policy_rule" "dealer" {
  auth_server_id       = okta_auth_server.dealer.id
  policy_id            = okta_auth_server_policy.dealer.id
  status               = "ACTIVE"
  name                 = "one_hour"
  priority             = 1
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["authorization_code", "implicit"]
  scope_whitelist      = ["*"]
}

resource "okta_auth_server_claim" "dealer" {
  auth_server_id          = okta_auth_server.dealer.id
  name                    = "groups"
  value_type              = "GROUPS"
  always_include_in_token = true
  group_filter_type       = "REGEX"
  value                   = ".*"
  claim_type              = "IDENTITY"
}

resource "okta_user_schema_property" "customfield1" {
  index       = "${local.nodash_subdomain}_${var.demo_app_name}_access_requests"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_access_requests"
  type        = "array"
  array_type  = "string"
  description = "${var.udp_subdomain}_${var.demo_app_name}_access_requests contains workflow request"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
}

resource "okta_group" "dealer_admin" {
  name        = "${local.nodash_subdomain}_${var.demo_app_name}_ADMIN"
  description = "Dealer Portal Administrator"
}

resource "okta_group_rule" "dealer_group_rule" {
  name              = "${var.udp_subdomain} ${var.demo_app_name} Admin Rule"
  status            = "ACTIVE"
  group_assignments = ["${okta_group.dealer_admin.id}"]
  expression_type   = "urn:okta:expression:1.0"
  expression_value  = "String.stringContains(user.email,\"okta.com\")"
}

resource "okta_group" "dealer_user" {
  name        = "${local.nodash_subdomain}_${var.demo_app_name}_USER"
  description = "Dealer Regular User"
}

resource "okta_group" "dealer_loc1" {
  name        = "${local.nodash_subdomain}_${var.demo_app_name}_LOC_Austin"
  description = "Austin, Texas Branch"
}

resource "okta_group" "dealer_loc2" {
  name        = "${local.nodash_subdomain}_${var.demo_app_name}_LOC_Chicago"
  description = "Chicago, Illinois Branch"
}

resource "okta_group" "dealer_loc3" {
  name        = "${local.nodash_subdomain}_${var.demo_app_name}_LOC_SF"
  description = "San Fransisco, California Branch"
}

resource "okta_group" "dealer_loc4" {
  name        = "${local.nodash_subdomain}_${var.demo_app_name}_LOC_WashingtonDC"
  description = "Washingthon DC Branch"
}

# Create the .env file
resource "local_file" "dotenv" {
  content = templatefile("${path.module}/dealer.dotenv.tpl", {
    client_id         = okta_app_oauth.dealer.client_id,
    client_secret     = okta_app_oauth.dealer.client_secret,
    domain            = format("%s.%s", var.org_name, var.base_url),
    auth_server_id    = okta_auth_server.dealer.id,
    okta_app_oauth_id = okta_app_oauth.dealer.id
  })
  # filename = "${path.module}/admin.env"
  filename = format("%s/%s.env", "${path.module}", var.demo_app_name)
}

# Output to the terminal
output "client_id" {
  value = okta_app_oauth.dealer.client_id
}

output "client_secret" {
  value     = okta_app_oauth.dealer.client_secret
  sensitive = true
}

output "domain" {
  value = "${var.org_name}.${var.base_url}"
}

output "auth_server_id" {
  value = okta_auth_server.dealer.id
}

output "issuer" {
  value = okta_auth_server.dealer.issuer
}

output "okta_app_oauth_id" {
  value = okta_app_oauth.dealer.id
}
