variable "org_name" {}
variable "api_token" {}
variable "base_url" {}
variable "demo_app_name" { default = "healthcare" }
variable "udp_subdomain" { default = "local" }

locals {
  app_domain       = var.udp_subdomain != "local" ? format("%s.%s.unidemo.info") : format("%s.%s", var.udp_subdomain, var.demo_app_name)
  nodash_subdomain = replace(var.udp_subdomain, "-", "_")
}

terraform {
  required_providers {
    okta = {
      source  = "okta/okta"
      version = "~> 3.17"
    }
  }
}

provider "okta" {
  org_name  = var.org_name
  api_token = var.api_token
  base_url  = var.base_url
}

data "okta_group" "all" {
  name = "Everyone"
}

resource "okta_app_oauth" "healthcare" {
  label       = format("%s DEMO (Generated by UDP)", local.app_domain)
  type        = "web"
  grant_types = ["authorization_code"]
  redirect_uris = [
    "https://${local.app_domain}/authorization-code/callback",
    "http://localhost:8666/authorization-code/callback"
  ]
  response_types = ["code"]
  consent_method = "TRUSTED"
  issuer_mode    = "ORG_URL"
  lifecycle {
    ignore_changes = [groups]
  }
}

resource "okta_app_group_assignment" "healthcare" {
  app_id   = okta_app_oauth.healthcare.id
  group_id = data.okta_group.all.id
}

resource "okta_trusted_origin" "healthcare" {
  name   = format("%s: 8666", local.app_domain)
  origin = "https://${local.app_domain}"
  scopes = ["REDIRECT", "CORS"]
}

resource "okta_auth_server" "healthcare" {
  name        = "${var.udp_subdomain} ${var.demo_app_name}"
  description = "Generated by UDP"
  audiences   = ["api://${local.app_domain}"]
}

resource "okta_auth_server_policy" "healthcare" {
  auth_server_id   = okta_auth_server.healthcare.id
  status           = "ACTIVE"
  name             = "standard"
  description      = "Generated by UDP"
  priority         = 1
  client_whitelist = [okta_app_oauth.healthcare.id]
}

resource "okta_auth_server_policy_rule" "healthcare" {
  auth_server_id       = okta_auth_server.healthcare.id
  policy_id            = okta_auth_server_policy.healthcare.id
  status               = "ACTIVE"
  name                 = "one_hour"
  priority             = 1
  group_whitelist      = [data.okta_group.all.id]
  grant_type_whitelist = ["authorization_code", "implicit"]
  scope_whitelist      = ["*"]
}

resource "okta_user_schema_property" "customfield1" {
  index       = "${local.nodash_subdomain}_${var.demo_app_name}_last_verified_date"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_last_verified_date"
  type        = "string"
  description = "Date Evident Last Verified"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
}

resource "okta_user_schema_property" "customfield2" {
  index       = "${local.nodash_subdomain}_${var.demo_app_name}_evident_id"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_evident_id"
  type        = "string"
  description = "Evident ID"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
  depends_on  = [okta_user_schema_property.customfield1]
}

resource "okta_user_schema_property" "customfield3" {
  index       = "${local.nodash_subdomain}_${var.demo_app_name}_dob"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_dob"
  type        = "string"
  description = "Date of Birth"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
  # depends_on  = [okta_user_schema_property.customfield2]
}

resource "okta_user_schema_property" "customfield4" {
  index       = "${local.nodash_subdomain}_${var.demo_app_name}_gender"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_gender"
  type        = "string"
  description = "Gender"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
  # depends_on  = [okta_user_schema_property.customfield3]
}

resource "okta_user_schema_property" "customfield5" {
  index       = "${local.nodash_subdomain}_${var.demo_app_name}_hasvisited"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_hasvisited"
  type        = "string"
  description = "Patient has visted facility"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
  # depends_on  = [okta_user_schema_property.customfield4]
}

resource "okta_user_schema_property" "customfield6" {
  index       = "${local.nodash_subdomain}_${var.demo_app_name}_consent"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_consent"
  type        = "string"
  description = "Date Patient Consensted HIPAA"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
  # depends_on  = [okta_user_schema_property.customfield5]
}

resource "local_file" "dotenv" {
  content = templatefile("${path.module}/healthcare.dotenv.tpl", {
    client_id         = okta_app_oauth.healthcare.client_id,
    client_secret     = okta_app_oauth.healthcare.client_secret,
    domain            = format("%s.%s", var.org_name, var.base_url),
    auth_server_id    = okta_auth_server.healthcare.id,
    okta_app_oauth_id = okta_app_oauth.healthcare.id
  })

  filename = format("%s/%s.env", "${path.module}", var.demo_app_name)
}

# Output to the terminal
output "client_id" {
  value = okta_app_oauth.healthcare.client_id
}

output "client_secret" {
  value     = okta_app_oauth.healthcare.client_secret
  sensitive = true
}

output "domain" {
  value = format("%s.%s", var.org_name, var.base_url)
}

output "auth_server_id" {
  value = okta_auth_server.healthcare.id
}

output "issuer" {
  value = okta_auth_server.healthcare.issuer
}

output "okta_app_oauth_id" {
  value = okta_app_oauth.healthcare.id
}
