variable "org_name" {}
variable "api_token" {}
variable "base_url" {}
variable "demo_app_name" {}
variable "udp_subdomain" {}
variable "test_app_domain" {}

#Comment for local testing and uncomment before commit.
terraform {
  backend "s3" {
  }
}

#For local testing, set app url correctly before commit.
locals {
    app_url = "${var.test_app_domain}"
    #app_url = "${var.udp_subdomain}.${var.demo_app_name}.unidemo.info"
}

provider "okta" {
  org_name  = "${var.org_name}"
  api_token = "${var.api_token}"
  base_url  = "${var.base_url}"
  version   = "~> 3.0"
}
provider "template" {
  version = "~> 2.1"
}
provider "local" {
  version = "~> 1.2"
}
data "okta_group" "all" {
  name = "Everyone"
}
resource "okta_app_oauth" "healthcare" {
  label          = "${var.udp_subdomain} ${var.demo_app_name} Demo (Generated by UDP)"
  type           = "web"
  grant_types    = ["authorization_code"]
  redirect_uris  = ["https://${local.app_url}/authorization-code/callback"]
  response_types = ["code"]
  issuer_mode    = "ORG_URL"
  groups         = ["${data.okta_group.all.id}"]
}
resource "okta_trusted_origin" "healthcare" {
  name   = "${local.app_url}"
  origin = "https://${local.app_url}"
  scopes = ["REDIRECT", "CORS"]
}
resource "okta_auth_server" "healthcare" {
  name        = "${var.udp_subdomain} ${var.demo_app_name}"
  description = "Generated by UDP"
  audiences   = ["api://${local.app_url}"]
}
resource "okta_auth_server_policy" "healthcare" {
  auth_server_id   = "${okta_auth_server.healthcare.id}"
  status           = "ACTIVE"
  name             = "standard"
  description      = "Generated by UDP"
  priority         = 1
  client_whitelist = ["${okta_app_oauth.healthcare.id}"]
}
resource "okta_auth_server_policy_rule" "healthcare" {
  auth_server_id       = "${okta_auth_server.healthcare.id}"
  policy_id            = "${okta_auth_server_policy.healthcare.id}"
  status               = "ACTIVE"
  name                 = "one_hour"
  priority             = 1
  group_whitelist      = ["${data.okta_group.all.id}"]
  grant_type_whitelist = ["authorization_code"]
  scope_whitelist      = ["*"]
}
data "template_file" "configuration" {
  template = "${file("${path.module}/healthcare.dotenv.template")}"
  vars = {
    client_id         = "${okta_app_oauth.healthcare.client_id}"
    client_secret     = "${okta_app_oauth.healthcare.client_secret}"
    domain            = "${var.org_name}.${var.base_url}"
    auth_server_id    = "${okta_auth_server.healthcare.id}"
    issuer            = "${okta_auth_server.healthcare.issuer}"
    okta_app_oauth_id = "${okta_app_oauth.healthcare.id}"
  }
}
resource "local_file" "dotenv" {
  content  = "${data.template_file.configuration.rendered}"
  filename = "${path.module}/healthcare.env"
}

resource "okta_user_schema" "customfield1" {
  index       = "${var.udp_subdomain}_${var.demo_app_name}_is_evident_validated"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_is_evident_validated"
  type        = "boolean"
  description = "Has Evident Validated User"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
}

resource "okta_user_schema" "customfield2" {
  index       = "${var.udp_subdomain}_${var.demo_app_name}_evident_id"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_evident_id"
  type        = "string"
  description = "Evident ID"
  master      = "OKTA"
  scope       = "SELF"
  permissions = "READ_WRITE"
  depends_on = ["okta_user_schema.customfield1"]
}

resource "okta_user_schema" "customfield3" {
  index       = "${var.udp_subdomain}_${var.demo_app_name}_dob"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_dob"
  type        = "string"
  description = "Date of Birth"
  master      = "OKTA"
  scope       = "SELF"
  permissions  = "READ_WRITE"
  depends_on = ["okta_user_schema.customfield2"]
}

resource "okta_user_schema" "customfield4" {
  index       = "${var.udp_subdomain}_${var.demo_app_name}_gender"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_gender"
  type        = "string"
  description = "Gender"
  master      = "OKTA"
  scope       = "SELF"
  permissions  = "READ_WRITE"
  depends_on = ["okta_user_schema.customfield3"]
}

resource "okta_user_schema" "customfield5" {
  index       = "${var.udp_subdomain}_${var.demo_app_name}_hasvisited"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_hasvisited"
  type        = "string"
  description = "Patient has visted facility"
  master      = "OKTA"
  scope       = "SELF"
  permissions  = "READ_WRITE"
  depends_on = ["okta_user_schema.customfield4"]
}

resource "okta_user_schema" "customfield6" {
  index       = "${var.udp_subdomain}_${var.demo_app_name}_consent"
  title       = "${var.udp_subdomain}_${var.demo_app_name}_consent"
  type        = "string"
  description = "Date Patient Consensted HIPAA"
  master      = "OKTA"
  scope       = "SELF"
  permissions  = "READ_WRITE"
  depends_on = ["okta_user_schema.customfield5"]
}