name: Pull Request Police
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 1
          labels: "type: breaking, type: feature, type: bug, type: maintenance, type: docs, type: dependencies"
